CREATE TABLE BLOODBANK (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    UNITS_AVAILABLE INT NOT NULL DEFAULT 0
);

CREATE TABLE DONORS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    CONTACT VARCHAR(15) NOT NULL,
    DONATION_DATE DATE
);

CREATE TABLE BLOODTRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BLOOD_GROUP VARCHAR(5) NOT NULL,
    UNITS INT NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE ENUM('DONATION', 'REQUEST') NOT NULL
);

CREATE TABLE ADMINS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL
);
